### ISSUE TITLE
DS_Store file

### ISSUE THREAD

**Issue by rovshango** [PacktPublishing/Hands-On-Enterprise-Automation-on-Linux#1]
Hello,

Can you include **.gitignore** file with **.DS_Store** content? 
MacOSX creates this file all the time.

**Comment by deepesh-packt** [comment]
Hey @rovshango,
With regards to your query, you can find the solution using the below link:
https://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder

Do get in touch in case of any queries.

Greetings!
